[tool.poetry]
name = "mlops-end-to-end"
version = "0.1.0"
description = ""
authors = ["Kevin <k.patyk@paulaschoice-eu.com>"]
readme = "README.md"
packages = [{include = "mlops_end_to_end", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "^6.29.5"
pandas = "^2.2.3"
scikit-learn = "^1.5.2"
scipy = "^1.14.1"
pandas-stubs = "^2.2.3.241009"
datetime = "^5.5"
jupyter = "^1.1.1"
pyspark = "^3.5.3"
mlflow = "^2.17.0"
numpy = ">=1.26.4, <2"
databricks-connect = "^15.4.2"
databricks-sdk = "^0.36.0"
databricks-feature-engineering = ">=0.6, <1"
pydantic = "^2.9.2"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pre-commit = "^4.0.1"
flake8 = "^7.1.1"
isort = "^5.13.2"
black = "^24.10.0"
mypy = "^1.13.0"
ruff = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
